name: Literature Review Helper CI

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]


jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - name: Hello World
        run: echo "Hello World!"
