name: Literature Review Helper CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]


jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - name: Pipeline Executed
        run: echo "Execution Not Implemented!"
